# ==============================================================================
# Project Name: Web Service Configuration of Movie Box Office Predictor
# Description: Website Node
# Author: Iorimiya
# Date: 2026-01-06
# Version: 1.0.0
# ==============================================================================
name:  mbop-website
services:
  mbop-website-node:
    image: php:apache
    container_name: mbop-website
    ports:
      - host_ip: ${host_ip}
        mode: host
        protocol: tcp
        published: 80
        target: 80
      - host_ip: ${host_ip}
        mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - type: bind
        source: ${website_host_path}
        target: /var/www/html/
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
