# ==============================================================================
# Project Name: Web Service Configuration of Movie Box Office Predictor
# Description: Website Node
# Author: Iorimiya
# Date: 2026-01-21
# Version: 1.1.2
# ==============================================================================
name:  mbop

services:
  website:
    build:
      context: ../../
      dockerfile: environments/website/Dockerfile
    image: iorimiya/mbop-website:v1.1.2
    ports:
      - mode: host
        host_ip: ${HOST_IP:-0.0.0.0}
        protocol: tcp
        # noinspection ComposeUnknownValues
        published: ${HOST_PORT:-80}
        target: 80
    volumes:
      - type: bind
        source: ${WEBSITE_HOST_PATH}
        target: /usr/share/nginx/html/
        read_only: true
    environment:
      TZ: Asia/Taipei
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
