import re
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from logging import Logger
from pathlib import Path
from typing import cast, Final, get_args, Iterator, Optional, TypeAlias

import requests
from bs4 import BeautifulSoup
from bs4.element import NavigableString, Tag
from requests import Response
from selenium.common.exceptions import StaleElementReferenceException
from tqdm import tqdm
from yaml import YAMLError

from src.core.constants import Constants
from src.core.logging_manager import LoggingManager
from src.data_collection.browser import CaptchaBrowser
from src.data_handling.file_io import YamlFile
from src.data_handling.movie_collections import MovieData
from src.data_handling.reply import Reply, ReplyRating
from src.data_handling.reviews import PublicReview
from src.utilities.collection_utils import delete_duplicate

Url: TypeAlias = str
RegularExpressionPattern: TypeAlias = str
Selector: TypeAlias = str


@dataclass(kw_only=True, frozen=True)
class _WebsiteConfig:
    """
    A data class to store configuration for a target website.

    :ivar base_url: The base URL of the website.
    :ivar search_url_part: The part of the URL used for searching.
    """
    base_url: str
    search_url_part: str


class TargetWebsite(Enum):
    """
    Enum representing the target website for review collection.

    Each member holds a _WebsiteConfig object containing site-specific URLs.
    """
    PTT = _WebsiteConfig(
        base_url='https://www.ptt.cc/bbs/movie/',
        search_url_part='search?q='
    )
    DCARD = _WebsiteConfig(
        base_url='https://www.dcard.tw/',
        search_url_part='search?forum=movie&query='
    )
    IMDB = _WebsiteConfig(
        base_url='https://www.imdb.com/',
        search_url_part='find/?q='
    )
    ROTTEN_TOMATO = _WebsiteConfig(
        base_url='https://www.rottentomatoes.com/',
        search_url_part='search?search='
    )


class ReviewCollector:
    """
    A class to collect reviews from various websites.

    It supports fetching reviews from PTT and Dcard, handling search key generation,
    URL retrieval, and parsing review content.

    :ivar __logger: The logger instance for logging messages.
    :ivar __search_target: The target website for review collection.
    """

    def __init__(self, target_website: TargetWebsite) -> None:
        """
        Initializes the ReviewCollector.

        :param target_website: The target website for review collection.
        """
        self.__logger: Logger = LoggingManager().get_logger('root')
        self.__search_target: TargetWebsite = target_website
        self.__logger.debug(f"ReviewCollector initialized for target: {self.__search_target.name}")

    @staticmethod
    def get_movie_search_keys(movie_name: str) -> list[str]:
        """
        Generates a list of potential search keys for a movie name.

        This method creates a comprehensive list of search terms. The original movie
        name is always included. Additional, derived keys are generated by handling
        patterns like "數位修復版", separators (e.g., ':', '-'), etc. These derived
        keys are then filtered to remove overly short or known noisy keywords.

        :param movie_name: The original name of the movie.
        :returns: A list of unique, high-quality search key strings.
        """

        logger: Logger = LoggingManager().get_logger('root')
        logger.debug(f"Creating search keys for '{movie_name}'.")

        # Constants and Patterns
        space: Final[RegularExpressionPattern] = " "
        empty: Final[RegularExpressionPattern] = ""
        dash: Final[RegularExpressionPattern] = "-"
        double_quotation: Final[RegularExpressionPattern] = "\""
        delete_pattern: Final[RegularExpressionPattern] = \
            "[\(（]((數位)?\s?(修復)?\s?(IMAX|A)?\s?((日|英|國)(文|語))?\s?((2|3)D)?\s?版?)+[\)）]$"
        separator_pattern: Final[RegularExpressionPattern] = "\s*[：:\-－]\s*"
        dual_double_quotation_pattern: Final[RegularExpressionPattern] = "\"{2}"
        start_with_double_quotation_pattern: Final[RegularExpressionPattern] = "^\""
        end_with_double_quotation_pattern: Final[RegularExpressionPattern] = "\"$"
        space_with_number_pattern: Final[RegularExpressionPattern] = " \d"

        # Preserve the original name as the primary, unfiltered key
        primary_key: str = re.sub(pattern=delete_pattern, repl=empty, string=movie_name)

        # Generate all other keys into a separate list for filtering
        derived_keys: list[str] = []

        if re.search(pattern=separator_pattern, string=primary_key) is not None:
            derived_keys.append(re.sub(pattern=separator_pattern, repl=empty, string=primary_key))
            derived_keys.append(re.sub(pattern=separator_pattern, repl=space, string=primary_key))
            derived_keys.append(re.sub(pattern=separator_pattern, repl=dash, string=primary_key))
            derived_keys.append(re.split(pattern=separator_pattern, string=primary_key)[1])

        if re.search(pattern=double_quotation, string=primary_key) is not None:
            if re.search(pattern=dual_double_quotation_pattern, string=primary_key) is not None:
                temp2 = re.sub(pattern=end_with_double_quotation_pattern, repl=empty,
                               string=re.sub(pattern=start_with_double_quotation_pattern, repl=empty,
                                             string=primary_key))
                derived_keys.append(re.sub(pattern=dual_double_quotation_pattern, repl=double_quotation,
                                           string=temp2))
                derived_keys.append(re.sub(pattern=dual_double_quotation_pattern, repl=space,
                                           string=temp2))
            derived_keys.append(re.sub(pattern=double_quotation, repl=empty, string=primary_key))

        if re.search(pattern=space_with_number_pattern, string=primary_key) is not None:
            derived_keys.append(re.sub(pattern=space, repl=empty, string=primary_key))

        # Filtering Logic (Applied only to derived keys)
        MIN_KEY_LENGTH: Final[int] = 3
        BLACKLIST: Final[list[str]] = ['re']

        logger.debug(
            f"Generated {len(derived_keys)} derived keys. Applying filters..."
        )

        filtered_derived_keys: list[str] = [
            key for key in delete_duplicate(items=derived_keys)
            if len(key) >= MIN_KEY_LENGTH and key.lower() not in BLACKLIST
        ]

        # Final Combination and De-duplication
        final_keys: list[str] = [primary_key] + filtered_derived_keys
        final_unique_keys: list[str] = delete_duplicate(items=final_keys)

        logger.debug(
            f"Finished creating {len(final_unique_keys)} unique search keys after filtering."
        )
        return final_unique_keys

    def __get_search_page_url(self, search_key: str) -> str:
        """
        Constructs the search page URL for the configured target website and a given search key.

        :param search_key: The search key (e.g., movie name) to be used in the URL.
        :returns: The fully constructed search page URL.
        """
        return f"{self.__search_target.value.base_url}{self.__search_target.value.search_url_part}{search_key}"

    def __get_bs_element(self, url: str) -> BeautifulSoup:
        """
        Fetches the content from a given URL and parses it into a ``BeautifulSoup`` object.

        Handles specific cookie requirements for certain sites (e.g., 'over18' for PTT).
        The response encoding is set based on ``response.apparent_encoding``.

        :param url: The URL from which to fetch the content.
        :returns: A ``BeautifulSoup`` object representing the parsed HTML content.
        :raises requests.exceptions.RequestException: For issues during the HTTP request (e.g., network problems, invalid URL).
        """
        # Some boards on PTT require the over18=1 cookie.
        response:Optional[Response] = None
        match self.__search_target:
            case TargetWebsite.PTT:
                response = requests.get(url=url, cookies={'over18': '1'})
            case _:
                response = requests.get(url=url)
        if response is not None:
            response.encoding = response.apparent_encoding
        else:
            msg: str = f"Failed to obtain a valid HTTP response from URL: '{url}'."
            self.__logger.error(msg)
            raise ValueError(msg)
        return BeautifulSoup(response.text, features='html.parser')

    def __get_largest_result_page_number(self, bs_root_element: BeautifulSoup) -> int:
        """
        Extracts the largest result page number from a PTT search results page.

        This method is specific to PTT's HTML structure for search pagination.
        It looks for a link with the text '最舊' to find the URL of the last page
        and then extracts the page number from that URL.

        :param bs_root_element: The ``BeautifulSoup`` object of a PTT search results page.
        :returns: The largest page number found in the pagination.
        :raises ValueError: If the ``self.__search_target`` is not ``TargetWebsite.PTT``.
        :raises IndexError: If the '最舊' link or the page number pattern is not found,
                            indicating an unexpected page structure or no pagination.
        :raises AttributeError: If the page number pattern is found but cannot be correctly parsed.
        """
        match self.__search_target:
            case TargetWebsite.PTT:
                re_pattern: Final[RegularExpressionPattern] = "page=(\d+)"
                key_word: Final[str] = '最舊'
                selector: Final[Selector] = "#action-bar-container a"
                last_page_url = \
                    [element['href'] for element in bs_root_element.select(selector) if element.text == key_word][0]
                return int(re.split(pattern='=', string=re.search(pattern=re_pattern, string=last_page_url)[0])[1])
            case _:
                raise ValueError

    def __get_review_urls(self, search_key: str, browser: Optional[CaptchaBrowser]) -> list[str]:
        """
        Gets a list of review URLs for a given search key from the target website.

        For PTT, it fetches URLs from all pages of search results.
        For Dcard, it uses a Selenium browser to scroll through search results and extract URLs.

        :param search_key: The search key (e.g., movie name) to find reviews for.
        :param browser: The browser instance to use for Dcard, or None for PTT.
        :returns: A list of unique review URLs. Returns an empty list if no URLs are found
                  or if an error occurs during PTT page number retrieval.
        :raises ValueError: If the ``self.__search_target`` is not ``TargetWebsite.PTT`` or ``TargetWebsite.DCARD``.
        :raises RuntimeError: If Dcard collection is attempted without a browser instance.
        """
        search_url: Url = self.__get_search_page_url(search_key=search_key)
        urls: list[str] = []
        match self.__search_target:
            case TargetWebsite.PTT:
                try:
                    max_page_number: int = self.__get_largest_result_page_number(self.__get_bs_element(url=search_url))
                except IndexError:
                    return list()
                self.__logger.debug(f"Found {max_page_number} pages of results for '{search_key}'.")
                domain_pattern: Final[RegularExpressionPattern] = '^[^:\/]+:\/\/[^\/]+'
                base_url: str = re.search(pattern=domain_pattern, string=self.__search_target.value.base_url).group(0)
                selector: Selector = "#main-container div.r-list-container div.title a"
                urls = [base_url + review['href']
                                   for current_page_number in range(1, max_page_number + 1)
                                   for review in
                                   self.__get_bs_element(url=f"{search_url}&page={current_page_number}").select(
                                       selector)]

            case TargetWebsite.DCARD:
                if not browser:
                    raise RuntimeError("A CaptchaBrowser instance is required for Dcard collection.")
                browser.get(url=search_url, captcha=True)
                selector: Selector = "div#__next div[role='main'] div[data-key] article[role='article'] h2 a[href]"
                scroll_height: int = int(browser.find_element(selector="body").get_attribute("scrollHeight"))
                for current_height in range(0, scroll_height, 150):
                    browser.execute_script(f"window.scrollTo(0,{current_height})")
                    new_urls:list[str] = []
                    for element in browser.find_elements(selector=selector):
                        try:
                            href: str = element.get_attribute("href")
                        except StaleElementReferenceException:
                            self.__logger.error(
                                f"StaleElementReferenceException for '{search_key}' at height {current_height}.",
                                exc_info=True)
                        else:
                            new_urls.append(href)
                    urls.extend(url for url in new_urls)
                urls = delete_duplicate(items=urls)

            case _:
                raise ValueError(f"Unsupported target website: {self.__search_target.name}")
        self.__logger.debug(f"Found {len(urls)} review URLs for '{search_key}'.")
        return urls

    def _parse_ptt_reply_time(self, reply_time_str: str, article_time: datetime) -> datetime:
        """
        Parses a PTT reply timestamp string into a datetime object.

        This method handles PTT's "MM/DD HH:MM" format and includes a heuristic
        to correct the year for replies made at the turn of the year.

        :param reply_time_str: The raw time string from the reply (e.g., " 01/14 09:19").
        :param article_time: The datetime object of the parent article, used to infer the year.
        :return: A datetime object for the reply.
        """
        reply_time_str = reply_time_str.strip()
        try:
            # Create a datetime object assuming the reply is in the same year as the article.
            reply_dt: datetime = datetime.strptime(f"{article_time.year} {reply_time_str}", "%Y %m/%d %H:%M")

            # Heuristic for year-end crossover: if the article is in December and the
            # reply is in January, assume the reply is from the following year.
            if article_time.month == 12 and reply_dt.month == 1:
                reply_dt = reply_dt.replace(year=article_time.year + 1)

            return reply_dt
        except ValueError:
            self.__logger.warning(f"Could not parse reply time '{reply_time_str}'. Using article time as fallback.")
            return article_time

    def __get_review_information(self, url: str, browser: Optional[CaptchaBrowser]) -> Optional[PublicReview]:
        """
        Extracts review information (title, content, post time, replies) from a given review URL.

        Supports PTT and Dcard. For Dcard, it uses a Selenium browser.
        The extracted information is used to create a ``PublicReview`` object.

        :param url: The URL of the review page.
        :param browser: The browser instance to use for Dcard, or None for PTT.
        :returns: A ``PublicReview`` object containing the extracted information,
                  or ``None`` if essential information cannot be found or an error occurs during parsing.
        :raises RuntimeError: If Dcard collection is attempted without a browser instance.
        """
        self.__logger.debug(f"Fetching review information from: \"{url}\".")
        title: Optional[str] = None
        content: Optional[str] = None
        posted_time: Optional[datetime] = None
        processed_replies: list[Reply] = []

        match self.__search_target:
            case TargetWebsite.PTT:
                meta_element_selector: Final[Selector] = '.article-metaline'
                meta_tag_selector: Final[Selector] = '.article-meta-tag'
                meta_value_selector: Final[Selector] = '.article-meta-value'
                push_selector: Final[Selector] = 'div.push'
                push_tag_selector: Final[Selector] = 'span.push-tag'
                push_content_selector: Final[Selector] = '.push-content'
                push_time_selector: Final[Selector] = '.push-ipdatetime'
                time_format: Final[str] = '%a %b %d %H:%M:%S %Y'
                key_words: Final[tuple[str, str]] = ('標題', '時間')
                try:
                    content_base_element: Optional[BeautifulSoup] = self.__get_bs_element(url=url).select_one(
                        selector='#main-content')
                    if not content_base_element:
                        self.__logger.warning(f"Could not find main content element in URL: \"{url}\".")
                        return None
                    article_meta_elements = content_base_element.select(selector=meta_element_selector)
                    for article_meta_element in article_meta_elements:
                        if article_meta_element.select_one(selector=meta_tag_selector).text == key_words[0]:
                            title = article_meta_element.select_one(selector=meta_value_selector).text
                        elif article_meta_element.select_one(selector=meta_tag_selector).text == key_words[1]:
                            posted_time = datetime.strptime(
                                article_meta_element.select_one(selector=meta_value_selector).text,
                                time_format)

                    if not posted_time:
                        self.__logger.warning(
                            f"Could not parse article post time from URL: \"{url}\". Cannot process replies.")
                        return None

                    content = ''.join(
                        [element for element in content_base_element if
                         isinstance(element, NavigableString)]).strip()

                    push_elements: list[Tag] = content_base_element.select(selector=push_selector)
                    for push in push_elements:
                        tag_element: Optional[Tag] = push.select_one(selector=push_tag_selector)
                        content_element: Optional[Tag] = push.select_one(selector=push_content_selector)
                        time_element: Optional[Tag] = push.select_one(selector=push_time_selector)

                        if not (content_element and time_element):
                            self.__logger.warning(f"Skipping incomplete reply in URL '{url}': {push.text.strip()}")
                            continue

                        rating: ReplyRating
                        if tag_element:
                            tag_text: str = tag_element.text.strip()
                            if tag_text in get_args(ReplyRating):
                                rating = cast(ReplyRating,tag_text)
                            else:
                                rating = "→"
                        else:
                            rating = "→"

                        reply_content: str = content_element.text.strip(': ')
                        reply_time_str: str = time_element.text.strip()
                        reply_time: datetime = self._parse_ptt_reply_time(reply_time_str, posted_time)

                        processed_replies.append(Reply(rating=rating, content=reply_content, created_at=reply_time))
                    if not (title and content):
                        return None
                except Exception as e:
                    self.__logger.warning(f"Cannot parse element in URL: \"{url}\".")
                    self.__logger.error(f"Error message: {e}", exc_info=True)
                    return None
            case TargetWebsite.DCARD:
                if not browser:
                    raise RuntimeError("A CaptchaBrowser instance is required for Dcard collection.")
                selector_base: Final[Selector] = "div#__next div[role='main']"
                selector_title: Final[Selector] = selector_base + " article h1"
                selector_time: Final[Selector] = selector_base + " article time"
                selector_content: Final[Selector] = selector_base + " article span"
                time_format: Final[str] = '%Y 年 %m 月 %d 日 %H:%M'

                browser.home()
                browser.get(url=url, captcha=True)

                try:
                    title = browser.find_element(selector=selector_title).text
                    posted_time = datetime.strptime(
                        browser.find_element(selector=selector_time).text,
                        time_format)
                    content = browser.find_element(selector=selector_content).text

                    # For now, we are not collecting Dcard replies as they don't fit
                    # the '推'/'噓'/'→' rating model. An empty list will be used.
                    processed_replies = []

                except Exception as e:
                    self.__logger.warning(f"Cannot find element in URL: \"{url}\".")
                    self.__logger.error(f"Error message: {e}", exc_info=True)
                    return None

        if title and content and posted_time:
            return PublicReview(
                url=url, title=title, content=content, created_at=posted_time.date(),
                replies=processed_replies, sentiment_score=None
            )
        return None

    def __get_reviews_by_keyword(self, search_key: str, browser: Optional[CaptchaBrowser]) -> list[PublicReview]:
        """
        Retrieves and processes all public reviews found using a specific search keyword.

        This method first gets all review URLs for the given ``search_key`` using ``__get_review_urls``,
        then iterates through these URLs to fetch detailed review information using ``__get_review_information``.
        Only successfully parsed reviews are returned.

        :param search_key: The keyword to search for reviews.
        :param browser: The browser instance to use for Dcard, or None for PTT.
        :returns: A list of ``PublicReview`` objects.
        :raises ValueError: If the ``self.__search_target`` is not ``TargetWebsite.PTT`` or ``TargetWebsite.DCARD``
                            (propagated from ``__get_review_urls``).
        """
        self.__logger.debug(f"Searching reviews with keyword: \"{search_key}\".")
        urls: list[str] = self.__get_review_urls(search_key=search_key, browser=browser)
        return list(filter(None, [self.__get_review_information(url=url, browser=browser) for url in
                                  tqdm(urls, desc=f'Fetching reviews for "{search_key}"',
                                       bar_format=Constants.STATUS_BAR_FORMAT)]))

    def __get_reviews_by_name(self, movie_name: str, browser: Optional[CaptchaBrowser]) -> list[PublicReview]:
        """
        Gets all unique public reviews for a given movie name.

        It first generates multiple search keys from the ``movie_name`` using ``get_movie_search_keys``.
        Then, for each search key, it fetches reviews using ``__get_reviews_by_keyword``.
        Finally, it consolidates and de-duplicates all found reviews.

        :param movie_name: The name of the movie.
        :param browser: The browser instance to use for Dcard, or None for PTT.
        :returns: A list of unique ``PublicReview`` objects. Returns an empty list if no reviews are found.
        """
        search_keys: list[str] = self.get_movie_search_keys(movie_name=movie_name)
        reviews: list[PublicReview] = [review for search_key in search_keys for review in
                                       self.__get_reviews_by_keyword(search_key=search_key, browser=browser)]
        self.__logger.debug(f"Found {len(reviews)} raw reviews for '{movie_name}'. De-duplicating...")
        reviews = delete_duplicate(items=reviews)
        self.__logger.debug(f"Finished with {len(reviews)} unique reviews for '{movie_name}'.")
        return reviews

    @contextmanager
    def _managed_browser_session(self) -> Iterator[Optional[CaptchaBrowser]]:
        """
        A context manager that provides a CaptchaBrowser session only if the target is DCARD.

        This centralizes the logic for browser instantiation and cleanup. For non-DCARD
        targets, it yields None and does nothing.

        :yields: A ``CaptchaBrowser`` instance if the target is DCARD, otherwise ``None``.
        """
        if self.__search_target == TargetWebsite.DCARD:
            browser: Optional[CaptchaBrowser] = CaptchaBrowser()
            try:
                browser.__enter__()
                yield browser
            finally:
                browser.__exit__(None, None, None)
        else:
            yield None

    def collect_reviews_for_movie(self, movie_name: str) -> list[PublicReview]:
        """
        Searches for public reviews for a single movie by name.

        This method fetches reviews for the specified movie. If no reviews are found,
        an empty list is returned. Any errors during the collection process will be raised.

        :param movie_name: The name of the movie.
        :returns: A list of PublicReview objects. Returns an empty list if no reviews are found.
        :raises Exception: Propagates any exceptions encountered during the review collection process.
        """
        self.__logger.debug(f"Starting single collection for movie: '{movie_name}'.")
        # noinspection PyArgumentList
        with self._managed_browser_session() as browser:
            reviews: list[PublicReview] = self.__get_reviews_by_name(movie_name=movie_name, browser=browser)
        self.__logger.debug(f"Finished collecting {len(reviews)} reviews for '{movie_name}'.")
        return reviews

    def collect_reviews_for_movies(self, movie_list: list[MovieData], data_folder: Path) -> None:
        """
        Collects public reviews for a list of movies and saves them to files.

        For each movie, it fetches reviews. If no reviews are found, an empty YAML file
        is created. If an error occurs during collection for a movie, it is logged,
        and the process continues to the next movie. CaptchaBrowser is instantiated
        only once for Dcard collection across all movies.

        :param movie_list: A list of MovieData objects for which to collect reviews.
        :param data_folder: The directory where the final data will be saved.
        """
        self.__logger.debug(f"Starting batch review collection for {len(movie_list)} movies.")
        data_folder.mkdir(parents=True, exist_ok=True)

        # noinspection PyArgumentList
        with self._managed_browser_session() as browser:
            for movie in tqdm(movie_list, desc='Collecting Reviews', bar_format=Constants.STATUS_BAR_FORMAT):
                self.__logger.debug(f"Processing reviews for movie ID {movie.id} ('{movie.name}').")
                try:
                    newly_fetched_reviews: list[PublicReview] = self.__get_reviews_by_name(
                        movie_name=movie.name, browser=browser
                    )

                    movie.update_public_reviews(update_method='EXTEND', data=newly_fetched_reviews)
                    saved_path: Path = movie.save_public_reviews(target_directory=data_folder)

                    if not newly_fetched_reviews:
                        self.__logger.debug(
                            f"No new reviews found for movie ID {movie.id}. Empty file created at '{saved_path}'.")
                    else:
                        self.__logger.debug(
                            f"Successfully collected and saved {len(newly_fetched_reviews)} reviews for movie ID {movie.id} to '{saved_path}'.")

                except Exception as e:
                    self.__logger.error(
                        f"Failed to collect reviews for movie ID {movie.id} ('{movie.name}'): {e}",
                        exc_info=True
                    )
                    empty_file_path: Path = data_folder / f"{movie.id}.yaml"
                    try:
                        YamlFile(path=empty_file_path).save(data=[])
                        self.__logger.debug(
                            f"Created empty review file for failed movie ID {movie.id} at '{empty_file_path}'.")
                    except (OSError, YAMLError) as file_e:
                        self.__logger.error(
                            f"Failed to create empty review file for movie ID {movie.id}: {file_e}",
                            exc_info=True)
