# thesis for zt
# box office predictions
# conda environment

name: thesis_for_zt
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
# python
  - defaults::python=3.10.15
  - defaults::ipython
  - defaults::pip=24.2
  - pip:
    - "selenium==4.26.1"
    - "PyYAML==6.0.2"
