# thesis for zt
# box office predictions
# conda environment

name: thesis_for_zt
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
# python
  - defaults::python=3.11
  - defaults::ipython
  - defaults::pip
  - defaults::tqdm
  - defaults::beautifulsoup4=4.12.3
  - defaults::requests=2.32.3
  - defaults::numpy=1.26.4
  - defaults::selenium=4.24.0
  - defaults::pyyaml
  - pip:
    - "tensorflow==2.18"

