# thesis for zt
# box office predictions
# conda environment

name: thesis_for_zt
dependencies:
# python
  - defaults::python=3.10.4
  - defaults::ipython
  - defaults::pip
  - pip:
    - "selenium==4.26.1"

