# Default configuration parameters for the box office prediction model training pipeline.
# These values are used when a training run is initiated without specific overrides.
# The 'model_id' must be provided by the user for each run and is not included here.

# --- Data Source & Processing ---
# The name of the source CSV file located in 'inputs/structured_datasets/'.
dataset_name: "dataset_2024"

# The number of past weeks' box office data to use for predicting the next week.
training_week_len: 8

# The ratios for splitting data into training, validation, and test sets.
# Format: [train_parts, validation_parts, test_parts]
# e.g., [8, 1, 1] means 80% train, 10% validation, 10% test.
split_ratios: [8, 1, 1]

# The seed for the random number generator to ensure reproducible data splits.
#random_state: 42


# --- Model Architecture ---
# The number of units (neurons) in the LSTM layer.
lstm_units: 50


# --- Training Process ---
# The total number of epochs to train the model.
epochs: 100

# The number of samples per gradient update.
batch_size: 32

# Verbosity mode for Keras training output. 0 = silent, 1 = progress bar, 2 = one line per epoch.
verbose: 1

# The interval in epochs at which to save model checkpoints.
# Set to null or remove the line to disable periodic checkpointing and only save the final model.
checkpoint_interval: 20
