# movie box office predictions and analysis system
# conda environment
# using LLM to analyse sentiment

name: movie_box_office_predictor-GPU
channels:
  - defaults
  - conda-forge
dependencies:
# python
  - defaults::python=3.10
  - defaults::ipython=8.30
  - defaults::pip=25.0
# web scraping
  - defaults::requests=2.32
  - defaults::beautifulsoup4=4.12
# compute
  - defaults::numpy=1.26
  - defaults::pandas=2.2
# tensorflow
  - conda-forge::cudatoolkit=11.7
  - conda-forge::cudnn=8.4
  - conda-forge::tensorflow=2.9.1=cuda*
  - defaults::scikit-learn=1.6
  - conda-forge::keras-preprocessing=1.1
# others
  - defaults::matplotlib=3.10.0
  - defaults::tqdm=4.66
  - defaults::openpyxl=3.1
  - defaults::pyyaml=6.0.2
  - conda-forge::openai
  - defaults::flask=3.1.2
  - pip:
    - "seleniumbase==4.34.16"
  